version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins-ansible/docker
    build:
      context: jenkins_ansible    
    ports:
      - "8090:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock 
    networks:
      - net
  remote_host:
    container_name: remote_host
    image: remote-host
    build:
      context: .
    networks:
      - net
  db_host:
    container_name: db
    image: mysql:5.7
    environment:
      - "MYSQL_ROOT_PASSWORD=12345"
    volumes:
      - "$PWD/jenkins_db:/var/lib/mysql"
    networks:
      - net
networks:
  net:
