def map = [
    stageA: 'ap-south-1',
    StageB: 'us-west-2'
]

pipeline {
    agent any
    // parameters {
    // }
    // environment {
    // }
    stages {
        stage ('SCM') {
            stage('checkout') {
                steps {
                    script{
                        dir("terraform")
                        {
                            git (
                                url: "https://github.com/raghib1992/Jenkins/jenkins-loop.git",
                                credentialsId: 'my-github-token',
                                branch: '*'
                            )
                        }
                    }
                }
            }
        }
        stage('loop'){
            steps{
                script {
                    map.each { entry ->
                        stage (entry.key) {
                            sh """
                                echo region = \\\"${entry.value}\\\" >> terraform.tfvars
                                """
                        }

                    }
                }
            }
        }
    }
}